version: '3.8'

services:
  web:
    build: .
    command: gunicorn djangoMultipleDatabase.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - postgres
      - redis

  celery_worker:
    build: .
    command: celery -A djangoMultipleDatabase worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A djangoMultipleDatabase beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis

  # Instead of using an image that may not have Flower in PATH,
  # we build our own image and run Flower as a celery subcommand.
  flower:
    build: .
    command: celery -A djangoMultipleDatabase flower --broker=redis://redis:6379/0
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - redis

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_PASSWORD: admin@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Map host port 6379 to container's internal port 6379 for simplicity.
  redis:
    image: redis:6
    restart: always
    ports:
      - "6380:6379"

volumes:
  mysql_data:
  postgres_data:
